#!/usr/bin/env python3
"""§16.5 `:712`／`:714` 步驟 4／`:716` 實測結果 → `docs/pre-registration.md` 的「附錄 C」（裁定 #66）。

讀 Hetzner `hetzner_stats.sh` 的兩份產出——`runs/stats/report_<TO>.json`（`score_stats.py`）與
`runs/stats/diag716_<TO>.json`（`score_diag716.py`，`:716` 被標組的族組成診斷）——生成附錄 C，
以 marker 包住、重跑整段覆寫。`--check` 只比對、不寫入：內容會變就 rc=1。

## 做法沿用附錄 B（`scripts/t717_appendix.py`）

- **每一個數字**都由 f-string 從兩份 JSON 算出（含組數、列數、sha256）；字面常數只剩規格常數
  （`:712` 的 [7.30, 92.70]、±0.01、`:716` 的三個門檻與 [45, 55]）與裁定編號。
- **會隨資料變真變假的定性斷言都配守門**（`_assert`／`raise` → `AppendixError` → rc=2），資料推翻它就中止，
  不會寫出一句被自己下面的表推翻的字。守門清單見 `docs/P3-CALIBRATION.md` §28。
- `:712`／`:714` **不是 PASS 就不產出**（rc=2）：那代表不該凍結，附錄不該存在。
- 確認狀態 `CONFIRMED` 與報告的須解釋組**雙向**比對：報告多一組（未裁定）或映射多一組（報告裡沒有）都中止。
- `tests/test_stats_appendix.py` 守「附錄內容＝重新產生的結果」。

## 附錄 C 放在哪裡

放在附錄 B 的 `t717_appendix` marker **之後**，用自己的 marker。`rank_table.py` 與 `t717_appendix.py` 的 splice
只換自己兩個 marker 之間的內容，不會吃掉附錄 C（測試另外守這一條）。

rc：0 成功（或 `--check` 無差異）／1 `--check` 有差異／2 中止（守門不過、讀不到檔、任何例外）。
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from iching.config import SEGMENTS  # noqa: E402  （純常數模組，不依賴 numpy）

REPORT = REPO / "runs" / "stats" / "report_2026-09-14.json"
DIAG = REPO / "runs" / "stats" / "diag716_2026-09-14.json"
PREREG = REPO / "docs" / "pre-registration.md"
BEGIN = "<!-- BEGIN stats_appendix (generated by scripts/stats_appendix.py — do not hand-edit) -->"
END = "<!-- END stats_appendix -->"

# ---- 規格常數（v1.2.2 §16.5 `:712`／`:716`；裁定 #65 ①）。報告表頭的值必須與之相同，否則中止 ----
RANGE_712 = (7.30, 92.70)
TOL = 0.01
BAND = [45.0, 55.0]
BOUNDARY_SHARE_MAX = 0.20
DISTINCT_MIN = 10
MODE_SHARE_MAX = 0.20
MODE_DECIMALS = 6
#: 裁定 #64 ①：樣本＝訓練＋驗證段（不是本檔自訂，取自 `iching.config.SEGMENTS`）。
SAMPLE = (SEGMENTS["train"][0], SEGMENTS["valid"][1])
SCHEMA = 1
LINES_PER_ROW = 6
#: 診斷 parity 容差的上限：`score_diag716.PARITY_TOL`＝1e-9，報告記的容差若更寬，「全數相符」的意義就變了。
PARITY_TOL_MAX = 1e-9
#: 列比例加總的浮點容差（加權估計的加總實測誤差 ~1e-14）。
SHARE_SUM_TOL = 1e-9
#: 報告與診斷之間同一個浮點欄（兩支程式各自由 db 算出）容許的差。
FIELD_TOL = 1e-12
TOP_K = 3

Key = tuple[str, str, str, str, str]

#: 須解釋組的確認狀態（v1.2.2 `:716`：須解釋）。**裁定 #66**（2026-09-24，使用者）：五組全部確認為預期行為。
#: 值為 None 時附錄標「待使用者確認」，不得替使用者認定。報告與本映射的組集合不相等 → 中止。
CONFIRMED: dict[Key, str | None] = {
    ("stock", "tpex", "short", "1", "reweighted"): "#66",
    ("stock", "twse", "short", "1", "reweighted"): "#66",
    ("stock", "twse", "swing", "1", "reweighted"): "#66",
    ("stock", "tpex", "short", "4", "reweighted"): "#66",
    ("stock", "tpex", "short", "5", "reweighted"): "#66",
}

#: 每組的說明型態（決定附錄用哪一段說明、配哪幾道守門）。集合必須與 `CONFIRMED` 相同。
#: - `single_sub`：族 A 只剩一個子指標、它在 S 端點 → 爻分數在登錄端點（初爻短線／波段）。
#: - `equal_subs`：單一值列的在場子指標值都等於最常出現值 → 加權平均＝該值。
#: - `fixed_pos`：單一值列只有一種簽名、在場子指標的截斷位置 u 固定且 c／d 單一 → 子指標分數固定 → 加權平均固定。
EXPLANATION: dict[Key, str] = {
    ("stock", "tpex", "short", "1", "reweighted"): "single_sub",
    ("stock", "twse", "short", "1", "reweighted"): "single_sub",
    ("stock", "twse", "swing", "1", "reweighted"): "single_sub",
    ("stock", "tpex", "short", "4", "reweighted"): "equal_subs",
    ("stock", "tpex", "short", "5", "reweighted"): "fixed_pos",
}

R_BOUND, R_DISTINCT, R_MODE = "達邊界比例 > 20%", "相異值數 < 10", "單一值佔比 > 20%"
ENDPOINT_STATUS = ("clip↑", "clip↓", "端點↑(未clip)", "端點↓(未clip)")


class AppendixError(Exception):
    pass


def _assert(cond: bool, what: str) -> None:
    if not cond:
        raise AppendixError(f"{what}——附錄裡對應的那句不成立或報告不可信，須人看")


def _need(d: dict, keys: tuple[str, ...], what: str) -> None:
    miss = [k for k in keys if k not in d]
    _assert(not miss, f"{what} 缺欄位 {miss}")


def _key(g: dict[str, Any]) -> Key:
    return (g["scope"], g["market"], g["horizon"], str(g["line"]), g["coverage"])


def _kname(k: Key) -> str:
    return f"{k[0]}/{k[1]}/{k[2]}/爻{k[3]}/{k[4]}"


def _p(x: float) -> str:
    return f"{x * 100:.2f}%"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _disp(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO).as_posix()
    except ValueError:
        return str(path)


# ---------------------------------------------------------------------------
# 獨立重算（刻意不 import score_stats：要核對的正是它的判定）
# ---------------------------------------------------------------------------
def recompute_714(g: dict[str, Any], tol: float) -> bool:
    reg = g.get("registry")
    return reg is not None and g["min"] >= reg[0] - tol and g["max"] <= reg[1] + tol


def recompute_716(g: dict[str, Any]) -> list[str]:
    """三個門檻皆嚴格不等式；理由順序同報告（達邊界／相異值／單一值）。"""
    out = []
    if g.get("share_at_boundary") is not None and g["share_at_boundary"] > BOUNDARY_SHARE_MAX:
        out.append(R_BOUND)
    if g["distinct"] < DISTINCT_MIN:
        out.append(R_DISTINCT)
    if g["mode_share"] > MODE_SHARE_MAX:
        out.append(R_MODE)
    return out


# ---------------------------------------------------------------------------
# 子指標簽名解析（`score_diag716` 的簽名格式：族以「；」分隔，族內「X{id 狀態｜…}」或「X 缺:原因」）
# ---------------------------------------------------------------------------
_FAM_PRESENT = re.compile(r"^([A-Z])\{(.*)\}$")
_FAM_MISSING = re.compile(r"^([A-Z]) 缺:(\S+)$")


def parse_signature(sig: str) -> list[tuple[str, list[tuple[str, str]] | str]]:
    """回 [(族, [(子指標, 狀態), …])｜(族, "缺:原因")]。子指標狀態：`clip↑`／`端點↓(未clip)`／`=50.0000`／`缺:missing`…"""
    out: list[tuple[str, list[tuple[str, str]] | str]] = []
    for part in sig.split("；"):
        m = _FAM_MISSING.match(part)
        if m:
            out.append((m.group(1), f"缺:{m.group(2)}"))
            continue
        m = _FAM_PRESENT.match(part)
        _assert(m is not None, f"子指標簽名無法解析：{sig!r}")
        subs = []
        for s in m.group(2).split("｜"):
            if "=" in s and " " not in s:
                sid, val = s.split("=", 1)
                subs.append((sid, f"={val}"))
            else:
                sid, _, st = s.partition(" ")
                _assert(bool(st), f"子指標簽名無法解析：{sig!r}")
                subs.append((sid, st))
        out.append((m.group(1), subs))
    return out


# ---------------------------------------------------------------------------
# 守門：報告自洽與兩份報告的綁定
# ---------------------------------------------------------------------------
def check_inputs(rep: dict[str, Any], diag: dict[str, Any], report_path: Path) -> None:
    _need(rep, ("schema", "sample", "tolerance", "band", "boundary_share_max", "distinct_min", "mode_share_max",
                "mode_decimals", "groups", "unknown", "summary", "data_version", "params_sha",
                "registry_model_versions"), "stats 報告")
    _need(diag, ("schema", "sample", "report", "data_version", "params_sha", "parity", "groups", "per_group", "seed",
                 "elapsed_s", "rss_peak_mib"), "診斷報告")
    _assert(rep["schema"] == SCHEMA and diag["schema"] == SCHEMA,
            f"報告 schema（stats {rep['schema']!r}／診斷 {diag['schema']!r}）≠ {SCHEMA}")
    # 規格常數：報告用的門檻不是規格的門檻，附錄寫的門檻就是錯的
    got = (rep["tolerance"], list(rep["band"]), rep["boundary_share_max"], rep["distinct_min"],
           rep["mode_share_max"], rep["mode_decimals"])
    want = (TOL, BAND, BOUNDARY_SHARE_MAX, DISTINCT_MIN, MODE_SHARE_MAX, MODE_DECIMALS)
    _assert(got == want, f"報告的門檻 {got} ≠ 規格常數 {want}")
    s = rep["sample"]
    _need(s, ("start", "end", "n_days", "first_day", "last_day", "rows"), "stats 報告 sample")
    _assert((s["start"], s["end"]) == SAMPLE, f"報告樣本段 {s['start']}～{s['end']} ≠ 裁定 #64 ① {SAMPLE[0]}～{SAMPLE[1]}")
    _assert(s["n_days"] > 0 and s["start"] <= s["first_day"] <= s["last_day"] <= s["end"], "落地日不在樣本段內或為 0 日")
    _assert((diag["sample"].get("start"), diag["sample"].get("end")) == SAMPLE, "診斷的樣本段 ≠ stats 報告")
    _assert(diag["data_version"] == rep["data_version"],
            f"診斷 data_version={diag['data_version']} ≠ stats {rep['data_version']}")
    _assert(diag["params_sha"] == rep["params_sha"], f"診斷 params_sha={diag['params_sha']} ≠ stats {rep['params_sha']}")
    _assert(Path(diag["report"]).name == report_path.name,
            f"診斷讀的報告 {diag['report']} 不是本附錄讀的 {report_path.name}")
    _assert(set(rep["registry_model_versions"]) == {"twse", "tpex"}, "registry_model_versions 不是 twse／tpex 兩市場")


def check_counts(rep: dict[str, Any]) -> None:
    g, sm, rows = rep["groups"], rep["summary"], rep["sample"]["rows"]
    _need(sm, ("groups_total", "groups_observed", "escape_712", "pass_712", "violations_714", "pass_714", "explain_716"),
          "stats 報告 summary")
    _assert(len({_key(x) for x in g}) == len(g), "報告 groups 有重複組鍵")
    _assert(sm["groups_total"] == len(g), f"groups_total={sm['groups_total']} ≠ groups 列數 {len(g)}")
    obs = [x for x in g if x["n"]]
    _assert(sm["groups_observed"] == len(obs), f"groups_observed={sm['groups_observed']} ≠ n>0 的組數 {len(obs)}")
    # 列數守恆：每列六爻，爻值不是進某一組就是記為未知（NULL）
    n_vals = sum(x["n"] for x in g) + sum(u["n"] for u in rep["unknown"])
    _assert(n_vals == LINES_PER_ROW * sum(rows.values()),
            f"各組 n＋未知爻 {n_vals:,} ≠ {LINES_PER_ROW}×列數 {LINES_PER_ROW * sum(rows.values()):,}")


def check_712(rep: dict[str, Any]) -> tuple[float, float, int]:
    obs = [x for x in rep["groups"] if x["n"]]
    esc = sum(x["escape_712"] for x in obs)
    sm = rep["summary"]
    _assert(esc == sm["escape_712"], f"各組 escape_712 加總 {esc} ≠ summary {sm['escape_712']}")
    _assert(sm["pass_712"] is (esc == 0), f"pass_712={sm['pass_712']} 與逸出 {esc} 筆不一致")
    lo, hi = min(x["min"] for x in obs), max(x["max"] for x in obs)
    _assert((lo >= RANGE_712[0] - TOL and hi <= RANGE_712[1] + TOL) is (esc == 0),
            f"逸出 {esc} 筆與全體極值 [{lo}, {hi}] 對規格範圍的判定不一致")
    _assert(sm["pass_712"] is True, f":712 FAIL（逸出 {esc} 筆）——不該凍結，不產出附錄")
    return lo, hi, esc


def check_714(rep: dict[str, Any]) -> list[dict[str, Any]]:
    obs = [x for x in rep["groups"] if x["n"]]
    bad = [_key(x) for x in obs if not recompute_714(x, rep["tolerance"])]
    _assert(all(x.get("within_registry_714") is recompute_714(x, rep["tolerance"]) for x in obs),
            "各組 within_registry_714 與極值／登錄區間重算不一致")
    _assert(sorted(bad) == sorted(_key(v) for v in rep["summary"]["violations_714"]),
            "summary.violations_714 與重算的越界組不一致")
    _assert(rep["summary"]["pass_714"] is (not bad), f"pass_714={rep['summary']['pass_714']} 與越界 {len(bad)} 組不一致")
    _assert(rep["summary"]["pass_714"] is True, f":714 步驟 4 FAIL（越界 {len(bad)} 組）——不該凍結，不產出附錄")
    return [x for x in rep["groups"] if not x["n"]]


def check_716(rep: dict[str, Any]) -> list[tuple[Key, dict[str, Any], list[str]]]:
    obs = [x for x in rep["groups"] if x["n"]]
    for x in obs:
        _assert(x.get("explain_716") == recompute_716(x), f"{_kname(_key(x))} 的 explain_716 與門檻重算不一致")
    want = [(_key(x), recompute_716(x)) for x in obs if recompute_716(x)]
    got = [(_key(e), list(e.get("reasons", []))) for e in rep["summary"]["explain_716"]]
    _assert(sorted(got) == sorted(want), "summary.explain_716 與各組門檻重算不一致")
    by = {_key(x): x for x in rep["groups"]}
    return [(k, by[k], r) for k, r in got]


def check_confirmed(flagged: list[Key]) -> None:
    fs = set(flagged)
    extra, gone = sorted(fs - set(CONFIRMED)), sorted(set(CONFIRMED) - fs)
    _assert(not extra, f"報告有未裁定的須解釋組 {[_kname(k) for k in extra]}")
    _assert(not gone, f"CONFIRMED 有報告中不存在的組 {[_kname(k) for k in gone]}")
    _assert(set(EXPLANATION) == set(CONFIRMED), "EXPLANATION 與 CONFIRMED 的組集合不同")


def check_diag(diag: dict[str, Any], flagged: list[tuple[Key, dict[str, Any], list[str]]]) -> dict[Key, dict[str, Any]]:
    dg = {_key(x): x for x in diag["groups"]}
    _assert(len(dg) == len(diag["groups"]), "診斷 groups 有重複組鍵")
    _assert(set(dg) == {k for k, _, _ in flagged}, "診斷的組與 stats 報告的須解釋組不一致")
    for k, g, reasons in flagged:
        d = dg[k]
        _need(d, ("reasons", "registry", "population", "n_sampled", "patterns", "boundary_rows", "mode_rows", "conclusion"),
              f"診斷 {_kname(k)}")
        _assert(list(d["reasons"]) == reasons, f"{_kname(k)}：診斷的理由 {d['reasons']} ≠ stats {reasons}")
        _assert(d["registry"] == g["registry"], f"{_kname(k)}：診斷的登錄區間 ≠ stats")
        pp = d["population"]
        _assert(pp["n"] == g["n"], f"{_kname(k)}：診斷母體 {pp['n']} ≠ stats n {g['n']}")
        for f in ("share_at_boundary", "mode_value", "mode_share"):
            _assert(abs(pp[f] - g[f]) <= FIELD_TOL, f"{_kname(k)}：診斷 {f}={pp[f]!r} ≠ stats {g[f]!r}")
        _assert(abs(sum(p["est_share"] for p in d["patterns"]) - 1.0) <= SHARE_SUM_TOL,
                f"{_kname(k)}：族缺值型態的佔母體比例加總不是 1")
        _assert(sum(sum(p["n_sample"].values()) for p in d["patterns"]) == d["n_sampled"],
                f"{_kname(k)}：族缺值型態的抽樣筆數加總 ≠ n_sampled")
        for blk, has in (("boundary_rows", pp["n_boundary"] > 0), ("mode_rows", pp["n_mode"] > 0)):
            sigs = d[blk]["signatures"]
            _assert(bool(sigs) is has, f"{_kname(k)}：{blk} 的簽名有無與母體列數不一致")
            if sigs:
                _assert(abs(sum(s["share"] for s in sigs) - 1.0) <= SHARE_SUM_TOL, f"{_kname(k)}：{blk} 簽名比例加總不是 1")
    par = diag["parity"]
    _need(par, ("rows", "max_abs_diff", "tol"), "診斷 parity")
    n_s = sum(x["n_sampled"] for x in diag["groups"])
    _assert(par["rows"] == n_s and n_s > 0, f"parity 列數 {par['rows']} ≠ 各組抽樣列數加總 {n_s}（或為 0）")
    _assert(par["tol"] <= PARITY_TOL_MAX, f"parity 容差 {par['tol']} 寬於 {PARITY_TOL_MAX}")
    _assert(par["max_abs_diff"] <= par["tol"], f"parity 最大差 {par['max_abs_diff']} 超過容差 {par['tol']}——診斷不可信")
    return dg


# ---------------------------------------------------------------------------
# 三種說明型態：每段文字配自己的守門
# ---------------------------------------------------------------------------
def _explain_single_sub(k: Key, g: dict, d: dict) -> list[str]:
    _assert(k[3] == "1" and k[2] in ("short", "swing") and k[4] == "reweighted",
            f"{_kname(k)}：「族 A 只剩一個子指標」的說明只適用於短線／波段個股初爻 reweighted")
    pats = d["patterns"]
    _assert(len(pats) == 1 and pats[0]["pattern"] == "A 在場" and abs(pats[0]["est_share"] - 1.0) <= SHARE_SUM_TOL,
            f"{_kname(k)}：族缺值型態不是 100% 的『A 在場』")
    endpoint_share = 0.0
    n_sig = 0
    for blk in ("boundary_rows", "mode_rows"):
        for s in d[blk]["signatures"]:
            fams = parse_signature(s["key"])
            _assert(len(fams) == 1 and fams[0][0] == "A" and isinstance(fams[0][1], list),
                    f"{_kname(k)}：簽名 {s['key']!r} 不是只有族 A")
            subs = fams[0][1]
            present = [(i, st) for i, st in subs if not st.startswith("缺:")]
            _assert(len(subs) == 2 and len(present) == 1 and present[0][1] in ENDPOINT_STATUS,
                    f"{_kname(k)}：簽名 {s['key']!r} 不是「一個缺、另一個在 S 端點」")
            if blk == "boundary_rows":
                n_sig += 1
                if present[0][1].startswith("端點"):
                    endpoint_share += s["share"]
    reg, mv = g["registry"], g["mode_value"]
    near = [i for i, e in enumerate(reg) if abs(mv - e) <= TOL]
    _assert(len(near) == 1, f"{_kname(k)}：最常出現值 {mv} 不在登錄區間任一端點 ±{TOL} 內")
    _assert(abs(reg[0] - RANGE_712[0]) <= TOL and abs(reg[1] - RANGE_712[1]) <= TOL,
            f"{_kname(k)}：登錄區間 {reg} 不是 S 全幅，「子指標在 S 端點 ⇒ 爻分數在登錄端點」不成立")
    _assert(d["strata"]["mode"]["population"] == 0, f"{_kname(k)}：有單一值列不是達邊界列（診斷 M 層非空）")
    end = "上界" if near[0] == 1 else "下界"
    return [
        f"- 族缺值型態 {_p(pats[0]['est_share'])} 為『A 在場』（實測）。短線／波段個股初爻的族權重只有族 A"
        "（程式現況：`src/iching/score/params.py` 的 `build_params` 設 `FW[(sc, h, \"1\")] = {\"A\": 1.0}`；"
        "不是本報告量測的數字）。",
        "- 本組為 reweighted＝族 A 的兩個子指標（`revenue_yoy`、`revenue_accel`）缺一個；族分數與爻分數都是加權平均"
        "（`src/iching/score/aggregate.py` 的 `family_score`／`line_score`），所以爻分數＝剩下那一個子指標的 S 值"
        "（由定義推得）。該子指標落在 S 端點時，爻分數就在登錄端點。",
        f"- 邊界列的子指標簽名 {n_sig} 種、單一值列的簽名，**全部**是「一個缺、另一個在 S 端點」（實測）；"
        f"邊界列中 clip 生效佔 {_p(1.0 - endpoint_share)}、未 clip 但子指標分數距 S 端點 ≤ {TOL} 佔 {_p(endpoint_share)}（加權估計）。",
        f"- 最常出現值 {mv:.6f} 即登錄{end}（實測，距端點 ≤ {TOL}），且單一值列全部也是達邊界列"
        "（診斷分層「只是單一值」層母體 0 列，實測）。",
    ]


def _explain_equal_subs(k: Key, g: dict, d: dict) -> list[str]:
    _assert(d["reasons"] == [R_MODE], f"{_kname(k)}：「在場子指標皆等於最常出現值」只說明單一值，本組還有其他理由")
    mv = round(g["mode_value"], 4)
    sigs = d["mode_rows"]["signatures"]
    for s in sigs:
        fams = parse_signature(s["key"])
        vals = [st for _, subs in fams if isinstance(subs, list) for _, st in subs]
        _assert(bool(vals) and all(st.startswith("=") and float(st[1:]) == mv for st in vals),
                f"{_kname(k)}：單一值列簽名 {s['key']!r} 的在場子指標不全等於 {mv}")
        _assert(any(isinstance(subs, str) for _, subs in fams), f"{_kname(k)}：簽名 {s['key']!r} 沒有缺席的族（不是 reweighted）")
    top = sigs[0]
    return [
        f"- 最常出現值 {g['mode_value']:.6f} 的列中 {_p(top['share'])} 為『{top['key']}』（實測）。",
        f"- 單一值列的子指標簽名 {len(sigs)} 種，**全部**是「在場子指標的值都等於 {mv:.4f}、至少一族缺席」（實測）；"
        "族分數與爻分數都是加權平均（`src/iching/score/aggregate.py` 的 `family_score`／`line_score`），"
        f"權重怎麼重配都得 {mv:.4f}（由定義推得）。",
        "- 子指標為什麼取這個值（情境表的哪一格、原始量是多少）：**未量測**。",
    ]


def _explain_fixed_pos(k: Key, g: dict, d: dict) -> list[str]:
    _assert(d["reasons"] == [R_MODE], f"{_kname(k)}：「截斷位置固定」只說明單一值，本組還有其他理由")
    sigs = d["mode_rows"]["signatures"]
    _assert(len(sigs) == 1, f"{_kname(k)}：單一值列不只一種簽名，「在場族與子指標相同」不成立")
    subs = d["mode_rows"]["subs"]
    _assert(bool(subs), f"{_kname(k)}：單一值列沒有在場子指標")
    for sid, e in subs.items():
        _assert(e["u_min"] is not None and e["u_min"] == e["u_max"], f"{_kname(k)}：{sid} 的 u 在單一值列上不固定")
        _assert(isinstance(e["c"], list) and len(e["c"]) == 1 and isinstance(e["d"], list) and len(e["d"]) == 1,
                f"{_kname(k)}：{sid} 的 c／d 不是單一值")
    by_u: dict[float, list[str]] = {}
    for sid, e in subs.items():
        by_u.setdefault(e["u_min"], []).append(f"`{sid.split('.', 1)[1]}`")
    ns = sorted({e["n_sample"] for e in subs.values()})
    pos = "；".join(f"u＝{u:g}".replace("-", "−") + f"：{'、'.join(ids)}" for u, ids in sorted(by_u.items(), key=lambda t: -t[0]))
    missing = [f"{f} {why}" for f, why in parse_signature(sigs[0]["key"]) if isinstance(why, str)]
    return [
        f"- 最常出現值 {g['mode_value']:.6f} 的列只有一種子指標簽名（{_p(sigs[0]['share'])}，實測）："
        f"『{sigs[0]['key']}』。",
        f"- 這些列上在場子指標的截斷位置 u 全部固定、c／d 各為單一值（實測，抽 {'／'.join(f'{n:,}' for n in ns)} 列）：{pos}。"
        f"缺席的族：{'、'.join(missing) if missing else '無'}。",
        "- 在場族與子指標相同、各子指標 x 相同 ⇒ 子指標分數相同 ⇒ 加權平均相同（由定義推得）。"
        + "".join(t for u, t in ((0.0, "u＝0 即 x＝c；"), (1.0, "|u|＝1 即 x 恰在截斷端點 c±3d；"))
                  if any(abs(v) == u for v in by_u))
        + "定義見診斷報告 `u_definition`。",
        "- x 為什麼恰落在這些位置（原始量是多少）：**未量測**。",
    ]


EXPLAINERS = {"single_sub": _explain_single_sub, "equal_subs": _explain_equal_subs, "fixed_pos": _explain_fixed_pos}


def _status(k: Key) -> str:
    c = CONFIRMED.get(k)
    return f"已確認為預期行為（{c}）" if c else "待使用者確認（凍結前必須補齊）"


# ---------------------------------------------------------------------------
# 生成
# ---------------------------------------------------------------------------
def build(rep: dict[str, Any], diag: dict[str, Any], report_path: Path, diag_path: Path) -> str:
    check_inputs(rep, diag, report_path)
    check_counts(rep)
    lo, hi, esc = check_712(rep)
    unobs = check_714(rep)
    flagged = check_716(rep)
    check_confirmed([k for k, _, _ in flagged])
    dg = check_diag(diag, flagged)
    s, sm, rows = rep["sample"], rep["summary"], rep["sample"]["rows"]
    obs = [x for x in rep["groups"] if x["n"]]
    mv = rep["registry_model_versions"]
    n_rows = sum(rows.values())
    L = ["## 附錄 C：§16.5 `:712`／`:714` 步驟 4／`:716` 實測結果（裁定 #64／#65／#66）", "",
         "**本節由 `scripts/stats_appendix.py` 從下列兩份報告生成，不得手改**（重跑會整段覆寫）。", "",
         "### 報告來源與綁定", "",
         "| 項目 | 值 |", "|---|---|",
         f"| stats 報告（`scripts/score_stats.py`） | `{_disp(report_path)}`（sha256 `{_sha256(report_path)}`） |",
         f"| 族組成診斷（`scripts/score_diag716.py`） | `{_disp(diag_path)}`（sha256 `{_sha256(diag_path)}`） |",
         f"| `data_version` | `{rep['data_version']}`（兩份相同） |",
         f"| `params_sha` | `{rep['params_sha']}`（兩份相同） |",
         f"| 登錄檔的 `model_version` | twse `{mv['twse']}`／tpex `{mv['tpex']}` |",
         f"| 樣本段（裁定 #64 ①） | {s['start']}～{s['end']}；落地 {s['n_days']:,} 日（{s['first_day']}～{s['last_day']}） |",
         f"| 列數 | 個股池內 {rows['stock_in_pool']:,}＋池外 {rows['stock_out_pool']:,}＋大盤 {rows['market_index']:,}"
         f"＝{n_rows:,} 列（×6 爻＝{LINES_PER_ROW * n_rows:,} 個爻值；其中未知爻 "
         f"{sum(u['n'] for u in rep['unknown']):,} 個不進統計） |", "",
         "兩份報告的 `data_version`／`params_sha`／樣本段相同、診斷讀的就是這份 stats 報告、"
         "須解釋組的母體數字（n、達邊界比例、最常出現值與其佔比、登錄區間）兩邊一致，本附錄才產出。"
         f"全文表（{len(rep['groups'])} 組，含五數、偏態、[45, 55] 比例）不貼入，見上列報告檔（同名 `.txt` 為同次產出的文字版）。", ""]

    # ---- :712 ----
    L += ["### `:712` 合法範圍", "",
          f"- 所有爻分數須落在 [{RANGE_712[0]:.2f}, {RANGE_712[1]:.2f}]（容許 ±{TOL}）：{len(obs)} 個有觀測組、"
          f"{sum(x['n'] for x in obs):,} 個爻值，逸出 **{esc}** 筆 → **PASS**（實測）。"
          f"全體最小值 {lo:.6f}、最大值 {hi:.6f}。",
          "- 同一行的後半「`N` 只套一次、`P_cs` 不套」不在 db 報告內（`scores.db` 不存子指標層），"
          "由 `tests/test_n_once.py` 驗（`docs/P3-CALIBRATION.md` §26）。", ""]

    # ---- :714 ----
    by_sc = Counter((x["scope"], x["coverage"]) for x in unobs)
    lines_sc: dict[tuple[str, str], set[str]] = {}
    for x in unobs:
        lines_sc.setdefault((x["scope"], x["coverage"]), set()).add(str(x["line"]))
    L += ["### `:714` 步驟 4：實測極值 vs 可達邊界登錄（`docs/score-ranges.md`）", "",
          f"- {sm['groups_observed']}／{sm['groups_total']} 組有觀測，越界 **{len(sm['violations_714'])}** 組 → **PASS**"
          f"（實測；容許 ±{TOL}，甲比甲、乙比乙）。",
          f"- 未觀測的 {len(unobs)} 組（樣本段內該爻從未以此 coverage 出現，n＝0）依 scope×coverage："]
    for (sc, cov), n in sorted(by_sc.items()):
        L.append(f"  - `{sc}`／`{cov}`：{n} 組（爻 {'、'.join(sorted(lines_sc[(sc, cov)]))}）")
    L.append("")

    # ---- :716 ----
    L += ["### `:716` 分布檢查", "",
          f"門檻（嚴格不等式）：達邊界比例 > {_p(BOUNDARY_SHARE_MAX)}、相異值數 < {DISTINCT_MIN}（規格 `:716`）；"
          f"單一值佔比 > {_p(MODE_SHARE_MAX)}（裁定 #65 ①：四捨五入到小數 {MODE_DECIMALS} 位後最常出現值的佔比）。"
          f"「達邊界」＝距登錄端點 ≤ {TOL}。{len(obs)} 個有觀測組中須解釋 **{len(flagged)}** 組：", "",
          "| 組 | n | 達邊界比例 | 相異值數 | 單一值佔比 @ 值 | 須解釋的理由 | 裁定 |",
          "|---|---:|---:|---:|---|---|---|"]
    for k, g, reasons in flagged:
        L.append(f"| {_kname(k)} | {g['n']:,} | {_p(g['share_at_boundary'])} | {g['distinct']:,} | "
                 f"{_p(g['mode_share'])} @ {g['mode_value']:.6f} | {'、'.join(reasons)} | {_status(k)} |")
    par = diag["parity"]
    L += ["", f"**族組成診斷的 parity**：每組分層抽樣（每組上限 {diag['per_group']:,} 列、seed "
          f"{diag['seed']}）共 {par['rows']:,} 列以真實計分程式碼重算該爻，與 db **全數相符**"
          f"（最大 |差| {par['max_abs_diff']!r}，容差 {par['tol']!r}）。診斷的比例一律是加權後的母體估計"
          f"（分層權重＝層母體列數 ÷ 層抽樣列數）。執行：耗時 {diag['elapsed_s']} s、RSS 峰值 {diag['rss_peak_mib']} MiB。", ""]

    for k, g, reasons in flagged:
        d = dg[k]
        pats = d["patterns"]
        L += [f"#### {_kname(k)}", "",
              f"母體 {g['n']:,} 列、抽樣 {d['n_sampled']:,} 列。", "",
              f"> 量測結論（診斷原句）：{d['conclusion']}", "",
              "| 族缺值型態 | 估計列數 | 佔母體 | 型態內達邊界 | 型態內單一值 |", "|---|---:|---:|---:|---:|"]
        for p in pats[:TOP_K]:
            L.append(f"| {p['pattern']} | {p['est_rows']:,.0f} | {_p(p['est_share'])} | {_p(p['boundary_share_within'])} | "
                     f"{_p(p['mode_share_within'])} |")
        if len(pats) > TOP_K:
            L.append(f"| （另 {len(pats) - TOP_K} 種） | {sum(p['est_rows'] for p in pats[TOP_K:]):,.0f} | "
                     f"{_p(sum(p['est_share'] for p in pats[TOP_K:]))} | | |")
        L.append("")
        L += ["**說明**：", ""] + EXPLAINERS[EXPLANATION[k]](k, g, d) + [f"- **{_status(k)}**", ""]

    # ---- 待量測：營收子指標的 u ----
    rev = []
    for k, _, _ in flagged:
        for blk, title in (("boundary_rows", "邊界列"), ("mode_rows", "單一值列")):
            for sid, e in dg[k][blk]["subs"].items():
                if sid.split(".", 1)[1].startswith("revenue_") and e["u_min"] is not None:
                    rev.append((k, sid, title, e))
    if rev:
        worst = max(rev, key=lambda t: max(abs(t[3]["u_min"]), abs(t[3]["u_max"])))
        wu = max(abs(worst[3]["u_min"]), abs(worst[3]["u_max"]))
        L += ["### 待量測事項：營收子指標的截斷位置 u（不影響上列裁定）", "",
              "診斷量到的營收子指標 u（`u＝direction·(x−c)／(3d)`；|u| > 1 即 x 在截斷範圍 [c−3d, c+3d] 外、clip 生效，"
              "|u|＝1 恰在端點；樣本內、**未加權**）：", "",
              "| 組 | 子指標 | 列類 | 抽 | u 最小 | u 中位 | u 最大 | d |", "|---|---|---|---:|---:|---:|---:|---|"]
        for k, sid, title, e in rev:
            L.append(f"| {_kname(k)} | `{sid}` | {title} | {e['n_sample']:,} | {e['u_min']:,.3f} | {e['u_median']:,.3f} | "
                     f"{e['u_max']:,.3f} | {'、'.join(map(str, e['d'])) if isinstance(e['d'], list) else e['d']} |")
        L += ["", f"- 最大 |u| 為 {wu:,.3f}（{_kname(worst[0])} 的 `{worst[1]}`，{worst[2]}）（實測）。",
              "- 這些列的爻分數被 clip 在 S 端點，不影響本附錄 `:712`／`:714` 的判定與上列裁定。"
              "原始 x 為什麼這麼大、有多少列受影響、要不要比照 EPS 的最小基期門檻：**未量測**"
              "（使用者裁定先量影響面再決定，見 `docs/P3-CALIBRATION.md` §28）。", ""]
    return "\n".join(L) + "\n"


def splice(doc: str, block: str) -> str:
    new = f"{BEGIN}\n{block}{END}\n"
    i, j = doc.find(BEGIN), doc.find(END)
    if i >= 0 and j > i:
        return doc[:i] + new + doc[j + len(END) + 1:]
    if i >= 0 or j >= 0:
        raise AppendixError("pre-registration.md 的 stats_appendix marker 只剩一半，請人看")
    return doc.rstrip("\n") + "\n\n" + new


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="附錄 C：:712／:714 步驟4／:716 實測結果（裁定 #66）")
    ap.add_argument("--report", default=str(REPORT))
    ap.add_argument("--diag", default=str(DIAG))
    ap.add_argument("--prereg", default=str(PREREG))
    ap.add_argument("--check", action="store_true", help="只比對、不寫入；內容會變就 rc=1")
    args = ap.parse_args(argv)
    try:
        rp, dp = Path(args.report), Path(args.diag)
        rep = json.loads(rp.read_text(encoding="utf-8"))
        diag = json.loads(dp.read_text(encoding="utf-8"))
        path = Path(args.prereg)
        doc = path.read_text(encoding="utf-8")
        new = splice(doc, build(rep, diag, rp, dp))
        if args.check:
            if new != doc:
                print("[stats_appendix] 附錄 C 與報告不一致，請重跑本腳本", file=sys.stderr)
                return 1
            print("== 附錄 C 與報告一致")
            return 0
        path.write_text(new, encoding="utf-8")
        print(f"== 附錄 C 已寫入 {path}（須解釋 {len(rep['summary']['explain_716'])} 組）")
        return 0
    except Exception as e:  # noqa: BLE001
        # 任何例外一律 rc=2，不得落到 rc=1（那是 --check 的「附錄過期」；同 t717_appendix）
        print(f"[stats_appendix 中止] {type(e).__name__}: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
