#!/usr/bin/env python3
"""§16.5 `:717` 門檻行為重驗結果 → `docs/pre-registration.md` 的「附錄 B」（裁定 #62）。

讀 `runs/t717/report_2026-09-14.json`（Hetzner `hetzner_t717.sh` 的產出），生成附錄 B，
以 marker 包住、重跑整段覆寫。`--check` 只比對、不寫入：內容會變就 rc=1。

## 為什麼是程式產生、不是手寫

附錄 A（卦別排序表）連退兩輪，同一個失效模式：**手寫的定性字句緊貼著計算出來的數字**，
於是文字被自己下面的表推翻（F1），修的時候又在同一段留下一句（G1）。本附錄的**每一個數字**
都由 f-string 從 JSON 算出（含格數）；字面常數只剩規格常數（10% 門檻、45／55 切線、84.16 下限、六爻）
與 ⑥ 的說明門檻 `HEX_GAP_MAX`。**會隨資料變真變假的定性斷言都配守門**（`_assert`／`raise`；清單見 P3-CALIBRATION §22），
資料推翻它就中止，不會寫出一句被自己下面的表推翻的字。節結構本身（哪幾項有逐項說明）也由 `EXPLAINED` 守。
`tests/test_t717_appendix.py` 守「附錄內容＝重新產生的結果」，所以附錄與 JSON 不可能脫鉤。

## 附錄 B 放在哪裡

放在附錄 A 的 `rank_table` marker **之後**，用自己的 marker。`rank_table.py` 的 splice
只換自己兩個 marker 之間的內容，不會吃掉附錄 B（測試另外守這一條）。

rc：0 成功（或 `--check` 無差異）／1 `--check` 有差異／2 中止。
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
REPORT = REPO / "runs" / "t717" / "report_2026-09-14.json"
PREREG = REPO / "docs" / "pre-registration.md"
BEGIN = "<!-- BEGIN t717_appendix (generated by scripts/t717_appendix.py — do not hand-edit) -->"
END = "<!-- END t717_appendix -->"

#: 各項是否已確認為「預期行為」（規格：>10% 須說明原因**並確認是預期行為**）。
#: 裁定 #62 使用者確認的是 ⑥⑦⑧；②⑤ 當時只在表裡給了解讀、**沒有請使用者確認**，
#: 不得替使用者認定——確認後把值改成裁定編號並重跑本腳本。
CONFIRMED: dict[str, str | None] = {
    "2_hysteresis_flips": None,
    "5_trigram_state_diff_rate": None,
    "6_hexagram_agreement": "#62",
    "7_candidate_overlap": "#62",
    "8_binding_rate": "#62",
}

ITEM_NAMES = {
    "1_line_state_diff_rate": "① 單爻陰陽態差異率",
    "2_hysteresis_flips": "② 遲滯翻爻次數",
    "3_flag_hit_rate": "③ 旗標觸發率",
    "4_moving_line_count_dist": "④ 動爻數分布",
    "5_trigram_state_diff_rate": "⑤ 內外卦方向判定差異率",
    "6_hexagram_agreement": "⑥ 主卦／前瞻式之卦一致率",
    "7_candidate_overlap": "⑦ 候選名單與名次重疊",
    "8_binding_rate": "⑧ 封頂／下限觸發率",
}


#: 附錄有「逐項說明」節的項目。超標項目集合必須**恰等於**它：少了＝某節會寫出空泛的「超標格…」句，
#: 多了＝「未超標」清單會與總覽表矛盾。不相等就中止、要人改寫節結構。
EXPLAINED = {"2_hysteresis_flips", "5_trigram_state_diff_rate", "6_hexagram_agreement",
             "7_candidate_overlap", "8_binding_rate"}


class AppendixError(Exception):
    pass


#: ⑥ 說明用的門檻：主卦／前瞻式之卦一致率與 (1−①)^6 的差都在此之內，才寫「⑥ 由 ① 解釋」。
#: **本附錄自訂的說明門檻，不是規格常數**；超過就中止、要人改寫說明。
HEX_GAP_MAX = 0.03


def _assert(cond: bool, what: str) -> None:
    if not cond:
        raise AppendixError(f"{what}——附錄裡對應的那句不成立，須改寫")


def _p(x: float) -> str:
    return f"{x * 100:.2f}%"


def _pp(x: float) -> str:
    return f"{x * 100:+.2f} 個百分點"


def _cell(r: dict) -> str:
    return f"{r['scope']}/{r['market']}/{r['horizon']}" + ("" if r["direction"] == "n/a" else f"/{r['direction']}")


def _status(item: str) -> str:
    c = CONFIRMED.get(item)
    return f"**已確認屬預期行為（裁定 {c}）**" if c else "**是否屬預期行為：待使用者確認**（凍結前必須補齊）"


def build(rep: dict[str, Any]) -> str:
    it, over = rep["items"], rep["over_threshold"]
    by_item: dict[str, list[dict]] = {}
    for h in over:
        by_item.setdefault(h["item"], []).append(h)
    _assert(set(by_item) == EXPLAINED, f"超標項目 {sorted(by_item)} 與附錄的逐項說明節不符")
    b, a, d = rep["before"], rep["after"], rep["dates"]
    thr = rep["big_diff_threshold"]
    L = ["## 附錄 B：§16.5 `:717` 門檻行為重驗結果（裁定 #62）", "",
         "**本節由 `scripts/t717_appendix.py` 從 `runs/t717/report_2026-09-14.json` 生成，不得手改**。",
         f"比對：同一段歷史 {d['first']}～{d['last']}（{d['n']:,} 日），**前側**＝校準前的 `d`"
         f"（`params_sha={b['params_sha']}`，`--uncalibrated`）、**後側**＝現行校準後的 `d`"
         f"（`params_sha={a['params_sha']}`）。`data_version={rep['data_version']}`。", "",
         f"規格（v1.2.2 §16.5）：任何一項差異 > {_p(thr)} 須逐項說明原因並確認是預期行為。"
         "⑥⑦ 的「差異」＝ 1 − 一致率。", ""]

    # ---- 可信度核對 ----
    hv = [r for r in it["3_flag_hit_rate"] if r["flag"] == "F-高波動"]
    oh = [r for r in it["3_flag_hit_rate"] if r["flag"] == "overheated"]
    hv_max = max(abs(r["diff"]) for r in hv)
    oh_max = max(abs(r["diff"]) for r in oh)
    _assert(hv_max == 0 and oh_max == 0, "F-高波動／overheated 前後側差不為零")
    L += ["### 報告可信度的兩項核對（實測）", "",
          f"- **比對到的列數**：個股 {rep['rows_matched']:,} 列＋大盤 {rep['market_rows_matched']:,} 列"
          f"＝{rep['rows_matched'] + rep['market_rows_matched']:,} 列。",
          f"- **不經過 `d` 的量，前後側差異為零**：`F-高波動`（{len(hv)} 格）與個股 `overheated`"
          f"（{len(oh)} 格）的前後觸發率差，最大絕對值分別為 {hv_max!r} 與 {oh_max!r}（原值，不是四捨五入）。"
          "這兩者由原始數值計算、不經 `d`，所以零差異代表分析工具沒有把不相干的東西算進去。", ""]

    # ---- 八項總覽 ----
    def rng(rows, key):
        vs = [r[key] for r in rows if r.get(key) is not None]
        return (min(vs), max(vs)) if vs else (None, None)
    L += ["### 八項總覽", "", "| 項目 | 格數 | 範圍 | 超標處數 |", "|---|---:|---|---:|"]
    spec = {"1_line_state_diff_rate": ("diff_rate", _p), "2_hysteresis_flips": ("rel_diff", _p),
            "3_flag_hit_rate": ("diff", _pp), "4_moving_line_count_dist": ("tv_distance", _p),
            "5_trigram_state_diff_rate": ("diff_rate", _p), "6_hexagram_agreement": ("king_wen_same_rate", _p),
            "7_candidate_overlap": ("jaccard", _p), "8_binding_rate": ("diff", _pp)}
    for k, (key, fmt) in spec.items():
        lo, hi = rng(it[k], key)
        L.append(f"| {ITEM_NAMES[k]} | {len(it[k])} | `{key}` {fmt(lo)}～{fmt(hi)} | {len(by_item.get(k, []))} |")
    L += ["", f"超標合計 **{len(over)}** 處。⑥⑦ 每格有兩個比較欄位（⑥ 主卦／前瞻式之卦；⑦ Jaccard／名次相同），"
          "超標以欄位計，所以超標處數可以大於格數。以下逐項說明。", ""]

    # ---- ② ----
    fl = by_item.get("2_hysteresis_flips", [])
    rows2 = {_cell(r): r for r in it["2_hysteresis_flips"]}
    stock2 = [r for r in it["2_hysteresis_flips"] if r["scope"] == "stock"]
    s_lo, s_hi = rng(stock2, "rel_diff")
    mk2 = [r for r in it["2_hysteresis_flips"] if r["scope"] == "market"]
    _assert(all(r["after"] > r["before"] for r in mk2), "② 大盤有格校準後翻爻沒有變多")
    L += [f"### {ITEM_NAMES['2_hysteresis_flips']}：超標 {len(fl)} 處", "",
          "| 格 | 前側 | 後側 | 絕對差 | 相對差 |", "|---|---:|---:|---:|---:|"]
    for h in fl:
        r = rows2[_cell(h)]
        L.append(f"| {_cell(h)} | {r['before']:,} | {r['after']:,} | {r['after'] - r['before']:+,} | {_p(r['rel_diff'])} |")
    if any(h["scope"] != "market" for h in fl):
        raise AppendixError("② 有 scope=stock 的超標格，附錄「全部在 market」那句不成立，須改寫")
    L += ["", f"- 超標格**全部在 `scope=market`**（實測，{len(fl)}/{len(fl)}）。大盤每個市場×期間只有一條序列，"
          f"前側翻爻次數為 {min(r['before'] for r in mk2):,}～{max(r['before'] for r in mk2):,} 次，"
          f"基數小，超標格的絕對差 {min(rows2[_cell(h)]['after'] - rows2[_cell(h)]['before'] for h in fl):+,}～"
          f"{max(rows2[_cell(h)]['after'] - rows2[_cell(h)]['before'] for h in fl):+,} 次就超過門檻（實測）。",
          f"- 同一項在個股層的相對差為 {_p(s_lo)}～{_p(s_hi)}（實測）。",
          f"- 大盤 {len(mk2)} 格校準後翻爻**全部變多**（實測）；成因**未量測**。",
          f"- {_status('2_hysteresis_flips')}", ""]

    # ---- ⑤ ----
    fl = by_item.get("5_trigram_state_diff_rate", [])
    l_lo, l_hi = rng(it["1_line_state_diff_rate"], "diff_rate")
    t_lo, t_hi = rng(it["5_trigram_state_diff_rate"], "diff_rate")
    _assert(t_lo > l_hi, "⑤ 最小值沒有高於 ① 最大值")
    L += [f"### {ITEM_NAMES['5_trigram_state_diff_rate']}：超標 {len(fl)} 處", "",
          "| 格 | 差異率 |", "|---|---:|"]
    L += [f"| {_cell(h)} | {_p(h['value'])} |" for h in fl]
    L += ["", f"- 全部 {len(it['5_trigram_state_diff_rate'])} 格範圍 {_p(t_lo)}～{_p(t_hi)}，整段高於 ① 單爻的 {_p(l_lo)}～{_p(l_hi)}（實測）。",
          "- 內外卦判定是三態（≥55／≤45／其間），比單爻陰陽多一條切線；三爻聚合分數在 45 或 55 附近移動"
          "都會改變狀態。這是 ⑤ 高於 ① 的**推測**原因，未另行量測。",
          f"- {_status('5_trigram_state_diff_rate')}", ""]

    # ---- ⑥ ----
    fl = by_item.get("6_hexagram_agreement", [])
    L1 = {(r["scope"], r["market"], r["horizon"]): r["diff_rate"] for r in it["1_line_state_diff_rate"]}
    if any(v > thr for v in L1.values()):
        raise AppendixError("① 有格超過門檻，附錄「① 全部不超過門檻」那句不成立，須改寫")
    L += [f"### {ITEM_NAMES['6_hexagram_agreement']}：超標 {len(fl)} 處", "",
          "一卦由六爻組成，只要一爻不同整卦就不同。若六爻大致獨立，主卦一致率 ≈ (1 − ① 單爻差異率)^6。"
          "逐格對照（實測）：", "",
          "| 格 | ① 單爻差異 | (1−①)^6 | 主卦一致率（實測） | 差 | 前瞻式之卦一致率（實測） | 差 |",
          "|---|---:|---:|---:|---:|---:|---:|"]
    gaps, fgaps = [], []
    for r in it["6_hexagram_agreement"]:
        k = (r["scope"], r["market"], r["horizon"])
        pred = (1 - L1[k]) ** 6
        gaps.append(r["king_wen_same_rate"] - pred)
        fgaps.append(r["future_king_wen_same_rate"] - pred)
        L.append(f"| {'/'.join(k)} | {_p(L1[k])} | {_p(pred)} | {_p(r['king_wen_same_rate'])} | "
                 f"{_pp(r['king_wen_same_rate'] - pred)} | {_p(r['future_king_wen_same_rate'])} | "
                 f"{_pp(r['future_king_wen_same_rate'] - pred)} |")
    _assert(max(abs(g) for g in gaps + fgaps) <= HEX_GAP_MAX, "⑥ 有格與 (1−①)^6 的差超過 HEX_GAP_MAX")
    L += ["", f"- {len(gaps)} 格主卦一致率與 (1−①)^6 的差在 {_pp(min(gaps))}～{_pp(max(gaps))}、"
          f"前瞻式之卦在 {_pp(min(fgaps))}～{_pp(max(fgaps))}，{len(gaps) + len(fgaps)} 個值都在 "
          f"{HEX_GAP_MAX * 100:.2f} 個百分點以內（實測；這是本附錄的說明門檻 `HEX_GAP_MAX`、不是規格常數）："
          "⑥ 的超標可以由 ① 的單爻差異解釋，不是另一個獨立的差異。",
          f"- 規格的 {_p(thr)} 門檻套在六爻組成的卦上，等於要求單爻差異約在 "
          f"{_p(1 - (1 - thr) ** (1 / 6))} 以下；而 ① 的 {len(L1)} 格全部不超過 {_p(thr)}（最大 {_p(l_hi)}）。",
          f"- **裁定 #62：⑥ 改以 ① 的單爻差異判定**，⑥ 本身的 {len(fl)} 處超標不再逐一判定。",
          f"- {_status('6_hexagram_agreement')}", ""]

    # ---- ⑦ ----
    fl = by_item.get("7_candidate_overlap", [])
    j_lo, j_hi = rng(it["7_candidate_overlap"], "jaccard")
    r_lo, r_hi = rng(it["7_candidate_overlap"], "same_rank_rate")
    L += [f"### {ITEM_NAMES['7_candidate_overlap']}：超標 {len(fl)} 處", "",
          "| 格 | Jaccard | 名次完全相同 | 比對日數 | 名額被乘成 0 的日數 | 兩側基本狀態不同的日數 |",
          "|---|---:|---:|---:|---:|---:|"]
    for r in it["7_candidate_overlap"]:
        L.append(f"| {_cell(r)} | {_p(r['jaccard'])} | {_p(r['same_rank_rate'])} | {r['n_days']:,} | "
                 f"{r['days_quota_zero']:,} | {r['days_basic_state_differs']:,} |")
    L += ["", f"- 候選名單（前 `floor(N0 × 名額連乘)` 名）的成員重疊 Jaccard 為 {_p(j_lo)}～{_p(j_hi)}，"
          f"名次完全相同的比例為 {_p(r_lo)}～{_p(r_hi)}（實測）。",
          "- **裁定 #62：接受為 c／d 校準的預期效果**——校準改變 `base_score` 的尺度，排序本來就會跟著變。",
          "- ⚠ **入場門檻 `T0` 未納入本項**（裁定 #59）：`T0` 的 48 格分位數 `q` 尚未定，"
          "本項只量 `N0` 名額層；`T0` 校準後須另行重驗。",
          f"- {_status('7_candidate_overlap')}", ""]

    # ---- ⑧ ----
    fl = by_item.get("8_binding_rate", [])
    floor_rows = [r for r in it["8_binding_rate"] if r["column"] == "floor_applied"]
    if any(r["n_before"] != r["n_after"] for r in floor_rows):
        raise AppendixError("⑧ floor_applied 前後側分母不同，附錄「分母相同」那句不成立，須改寫")
    cap_rows = [r for r in it["8_binding_rate"] if r["column"] == "overheat_cap_applied"]
    # over_threshold 的 ⑧ 條目不帶 column，同一格有 floor／cap 兩列。本節文字只說明下限，所以：
    # ①封頂列一律不得超標；②每個超標格都要有一列超過門檻的 floor_applied（● 才標得到對的列）。
    _assert(all(abs(r["diff"]) <= thr for r in cap_rows), "⑧ overheat_cap_applied 有格超標，本節只說明下限")
    flagged_floor = []
    for h in fl:
        hit = [r for r in floor_rows if _cell(r) == _cell(h) and abs(r["diff"]) > thr]
        _assert(len(hit) == 1, f"⑧ 超標格 {_cell(h)} 找不到超過門檻的 floor_applied 列")
        flagged_floor.append(hit[0])
    _assert(all(r["after"] > r["before"] for r in flagged_floor), "⑧ 超標格的後側觸發率沒有較高")
    c_lo, c_hi = rng(cap_rows, "diff")
    L += [f"### {ITEM_NAMES['8_binding_rate']}：超標 {len(fl)} 處", "",
          "| 格 | 欄 | 前側 | 後側 | 差 | 分母 | 超標 |", "|---|---|---:|---:|---:|---:|---|"]
    flagged8 = {_cell(r) for r in flagged_floor}
    for r in floor_rows:
        L.append(f"| {_cell(r)} | `floor_applied` | {_p(r['before'])} | {_p(r['after'])} | {_pp(r['diff'])} | "
                 f"{r['n_before']:,} | {'●' if _cell(r) in flagged8 else ''} |")
    L += ["", "- 下限只在中期期間的初爻、套在**族 A（月營收 YoY＋加速度）的分數**上，不是 `base_score` 欄"
          "（`src/iching/score/stock.py` 的 `revenue_high_floor`）：月營收創 12 個月新高、而族 A 分數低於 84.16 時，"
          "族 A 分數被撐到 84.16，記 `floor_applied=1`。",
          "- 分母是「創高日 ∩ 族 A 有分數日」（§18），不是所有中期個股日；前後側分母相同（實測）。",
          "- 超標格的後側觸發率較高（實測），代表校準後有更多創高日的族 A 分數落在 84.16 以下（由定義推得）。"
          "族 A 分數分布為什麼這樣移動：**未量測**。",
          f"- 過熱封頂 `overheat_cap_applied` 的差為 {_pp(c_lo)}～{_pp(c_hi)}，{len(cap_rows)} 格全部未超標（實測）。",
          f"- {_status('8_binding_rate')}", ""]

    # ---- 未超標 ----
    rest = [k for k in ITEM_NAMES if k not in by_item]
    L += [f"### 未超標的 {len(rest)} 項（實測）", ""]
    for k in rest:
        key, fmt = spec[k]
        lo, hi = rng(it[k], key)
        L.append(f"- {ITEM_NAMES[k]}：`{key}` {fmt(lo)}～{fmt(hi)}，{len(it[k])} 格全部未超標。")
    L.append("")
    return "\n".join(L) + "\n"


def splice(doc: str, block: str) -> str:
    new = f"{BEGIN}\n{block}{END}\n"
    i, j = doc.find(BEGIN), doc.find(END)
    if i >= 0 and j > i:
        return doc[:i] + new + doc[j + len(END) + 1:]
    if i >= 0 or j >= 0:
        raise AppendixError("pre-registration.md 的 t717_appendix marker 只剩一半，請人看")
    return doc.rstrip("\n") + "\n\n" + new


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="附錄 B：:717 門檻行為重驗結果（裁定 #62）")
    ap.add_argument("--report", default=str(REPORT))
    ap.add_argument("--prereg", default=str(PREREG))
    ap.add_argument("--check", action="store_true", help="只比對、不寫入；內容會變就 rc=1")
    args = ap.parse_args(argv)
    try:
        rep = json.loads(Path(args.report).read_text(encoding="utf-8"))
        path = Path(args.prereg)
        doc = path.read_text(encoding="utf-8")
        new = splice(doc, build(rep))
        if args.check:
            if new != doc:
                print("[t717_appendix] 附錄 B 與報告不一致，請重跑本腳本", file=sys.stderr)
                return 1
            print("== 附錄 B 與報告一致")
            return 0
        path.write_text(new, encoding="utf-8")
        print(f"== 附錄 B 已寫入 {path}（超標 {len(rep['over_threshold'])} 處）")
        return 0
    except (AppendixError, OSError, ValueError, KeyError) as e:
        print(f"[t717_appendix 中止] {type(e).__name__}: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
